### ISSUE TITLE
When I try to create an onInterval workflow, the cron expression input doesn't appear

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#1225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.0

### Current Behavior

onInterval input doesn't show up. 

All existing interval workflows work. Modifying the workflow config via the database is my current (ugly) workaround.

### Expected Behavior

Input shows up allowing for cron expression input

### Anything else?

See attached video

https://github.com/cortezaproject/corteza/assets/19151369/4a9c0a96-34dd-4726-8bf7-c691a42639ab

**Comment by Fajfa** [comment]
Was fixed with [#fe6ab0c](https://github.com/cortezaproject/corteza/commit/fe6ab0c0dd7dcc9719237944053df5967426006d)
Will be released in `2023.3.2` next week
Thank you for reporting it, should have been caught earlier by us...

If you need a workaround, you can export the wf, and edit it in a text editor where you can add a constraint for the trigger. 
```
"triggers": [
        {
          "resourceType": "compose",
          "eventType": "onInterval",
          "constraints": [
            {
              "name": "",
              "op": "=",
              "values": [
                ""
              ]
            }
          ],
          ...
          
```

If you import the edited workflow the input should appear
