### ISSUE TITLE
DAL: cannot set alterations for default schema

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1288]
## Conclusions
This happens because the module hasn't been saved yet

## Reproduction steps

![Image](https://user-images.githubusercontent.com/85161724/250586076-0aa38fa1-48a3-4e6b-bcc9-f6dd299e0537.gif)

**Comment by tjerman** [comment]
That's not true. One of the checks I've added in there is to prevent users from modifying the default built-in table we use for records (`compose_records` table). Since you didn't change the connection, nor specify where it should be stored to, it assumes you want to change up the primary one (since you used an alias in there).

I don't think we should be touching that one since it could bring a bunch of complications later down the line so I'd suggest we simply disable most of the UI to prevent these alterations on primary connections.

**Comment by tjerman** [comment]
@katrinDY closing this; we should make a new issue for front-end
