### ISSUE TITLE
Add option to provide custom color scheme to charts

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1410]
In compose ChartConfigurator add a way to create custom chart themes.

Open theme creation(color pickers) in a modal, on modal save, save the theme to compose settings.
This theme must then be available in the color picker to pick and use.

Related files:
- `client/web/compose/src/views/Admin/Charts/Edit.vue` 
On line ~100  you'll find the current color picker

This is the view where all of this should happen, except for the modal which would preferably be a separate component (so it can be reusable) for example `client/web/compose/src/components/Chart/ThemeModal.vue` (or something like that)

**Comment by nagxsan** [comment]
Hi @katrinDY ! I would like to take this issue up, could you please let me know a small brief about the issue raised?

**Comment by Fajfa** [comment]
Hello @daredevil0905, I added a bigger description to the issue, if you need more help do say.
One small thing to add, this is meant for 2023.3.9 which be released end of September. If you can implement it in the next two weeks, otherwise we'll be forced to take over due to the intended release date.

**Comment by nagxsan** [comment]
Thank you @Fajfa ! I will surely try to implement it in the given timeline

**Comment by nagxsan** [comment]
Hey @Fajfa ! I am really thankful for your opportunity, however due to some other commitments I would not be able to contribute to this issue fully and wholeheartedly as I would want to. And I did not want to waste the crucial time that you have so I wanted to let you know just now itself. I am really sorry for this and I will surely make it up by contributing to a different issue in future.
