### ISSUE TITLE
High CPU usage when modifying custom CSS

### ISSUE THREAD

**Issue by moalamri** [cortezaproject/corteza#1713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.9

### Current Behavior

When editing the Custom CSS, most of the time it runs ok, but sometimes it takes alot of time before returning a timeout, I monitored the server resources and it shows as following
![IMG_7318](https://github.com/cortezaproject/corteza/assets/964077/e6b58922-62fb-4bd6-a26b-0f00317199a3)

### Steps To Reproduce

1. Change Custom CSS
2. Hit Submit

**Comment by Fajfa** [comment]
Ok thanks, we'll take a look at that. Strange since it works without much processing on my end

**Comment by moalamri** [comment]
Hi @Fajfa 
Whenever this happens, I check the action log and it's filled with such records

![image](https://github.com/cortezaproject/corteza/assets/964077/5836e436-5dca-443e-b9db-93e66b6b1405)

Please let me know if I can do anything else to helps you debug this
Thank you

**Comment by Fajfa** [comment]
https://forum.cortezaproject.org/t/dart-processes-running-forever/1934

**Comment by moalamri** [comment]
@Fajfa I’m sorry for closing the issue earlier because I thought it was from my setup. Glad to see that you have spotted the issue.

**Comment by KinyaElGrande** [comment]
@moalamri 

I believe the root of the issue lies within Dart-Sass, particularly regarding the specific versions of Dart-Sass you're using.
Could you please provide the dart-sass version and if possible the style sheets as well?

I've repeteadly updated my stylesheets on corteza's `custom-css-editor ` to lines spanning more than 25k while monitoring  my CPU, which showed a steady pattern of spikes and drops.

Furthermore, there have been documented reports of CPU performance issues associated with Dart-Sass, as indicated by various issues such as:

- [Issue 1557](https://github.com/sass/dart-sass/issues/1557)
- [Issue 1534](https://github.com/sass/dart-sass/issues/1534)
- [Issue 1913](https://github.com/sass/dart-sass/issues/1913)

Nevertheless, the Dart-Sass team asserts that many of these performance issues have been addressed in versions beyond v1.61.0.


### Corteza's custon-css-editor screenshot

![Screenshot 2024-05-17 at 17 33 07](https://github.com/cortezaproject/corteza/assets/32476094/83dfc904-fdb9-4ec0-be19-eeef73ee88c8)


### CPU metrics screenshot
![Screenshot 2024-05-17 at 17 37 51](https://github.com/cortezaproject/corteza/assets/32476094/5731d142-58f9-48d7-aa11-4143a4e510be)

**Comment by moalamri** [comment]
Hey @KinyaElGrande 
I'm sorry for not being able to reproduce this again since I don't using Corteza for now and I remember it was a bit tricky to get it up and running because of `proxy` network is not being created or something, so I can't setup it again for further debugging.

I remember my Custom CSS was only few lines ~10 line or so. So, it wasn't a matter of payload size...
I wish I could be more helpful. I hope you can figure the issue and fix it if it does exist with other users.

**Comment by KinyaElGrande** [comment]
I believe this issue is related to  https://github.com/cortezaproject/corteza/issues/1856, which has been resolved.

**Comment by moalamri** [comment]
@KinyaElGrande You can close this issue and I will reopen it once I test the platform again and confirm if the issue still exists.
