### ISSUE TITLE
Allow integrators to duplicate, copy and paste page blocks [PlanID:2023.3/34/3]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#447]
When using page-builder, an integrator can see two new icons between edit and delete - **clone** and **copy**.

![Image](https://user-images.githubusercontent.com/1500447/198826156-06b3e332-c9f0-4be7-b24a-4ec2a09e6b55.png)

 - [x] Add the two new icons (use proper icons for duplicate and copy)
 - [x] Support **block cloning**
 - [x] Support block copy-to-clipboard; write JSON representation of the block to the clipboard for cross-app **and**
 - [x] Show temporary **success** toast when block is copied 
 - [x] Show **info** toast that there is a page-block waiting
 - [x] Support paste from clipboard

New blocks added with paste or clone should be placed at the end of the grid.

Keep in mind that it is highly probable that this functionality will be added to other resource types and elements on frontend.

**Comment by EmmyMay** [comment]
![image](https://user-images.githubusercontent.com/31524469/200647412-b3b63ffc-4da4-46b9-ad77-3566a1ad4a2f.png)

**Comment by EmmyMay** [comment]
![image](https://user-images.githubusercontent.com/31524469/201056079-acacbc70-45c4-4483-9376-952d1cecb88a.png)
https://github.com/web-platform-tests/interop/issues/143

Reading from the clipboard is still inconsistent across browsers. Reading the clipboard to let the user know if there is a page-block awaiting looks undoable for now. I want to move forward by just displaying the two toasts to them for now.

**Comment by EmmyMay** [comment]
https://github.com/cortezaproject/corteza-webapp-compose/pull/453 for issue #447

**Comment by EmmyMay** [comment]
Corteza-locale updated

**Comment by EmmyMay** [comment]
https://github.com/cortezaproject/corteza/pull/514 for issue https://github.com/cortezaproject/corteza/issues/447

**Comment by EmmyMay** [comment]
Changelog Documentation

### What was added?
The ability to copy, clone, and paste page blocks in page builders.

### Why was it added?
To make it possible to duplicate page blocks easily.

### What changed?
The toolbox for page blocks now has more icons.

### Why did it change?
These icons make it so that these new features are easily accessible.

### How did it change?
You'll find that there are more icons now than the usual two of edit and delete.

**Comment by Bojan-Svirkov** [comment]
I went through this and the feature is working nicely I just have one note in regards to the ability for resizing the block. So @EmmyMay please look into this since when the block is resized into it's smaller form after that you cannot resize it since the button for resizing is covered by the other modal which is above it. Please look into the video:

![image](https://user-images.githubusercontent.com/53232926/204792986-9cd27057-e621-451a-ac11-055f06424de1.png)


[c9816f3c-4b29-4bf4-a996-fd4b1def1a9c.webm](https://user-images.githubusercontent.com/53232926/204792906-bdf46010-a138-4130-b61e-b9bb4b67b59b.webm)

**Comment by EmmyMay** [comment]
Nice catch @Bojan-Svirkov. I'll look into it

**Comment by EmmyMay** [comment]
Per the issue raised by @Bojan-Svirkov, there is no less hacky way as far as I investigated to fix that except to tweak the toolbox for the general view.

@Fajfa

**Comment by darh** [comment]
Maybe a few pixels less on padding/margin will help - in general, not only on the narrow version?

**Comment by EmmyMay** [comment]
> Maybe a few pixels less on padding/margin will help - in general, not only on the narrow version?

Joze suggested something different that I think is even better. Will push once I get it working.

**Comment by EmmyMay** [comment]
@Bojan-Svirkov The issue has been fixed. Toolbox still overlays the block but it should not get in the way now.

**Comment by Bojan-Svirkov** [comment]
@EmmyMay I just tested this and yes now I can resize the blocks and I guess we can be happy with this solution. I also added the CL entry so I am moving the card to Done. Once you merge everything feel free to close this issue.
