### ISSUE TITLE
Allow end-users to open records in a modal window [PlanID:2023.3/2/4.3]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#448]
Record list can be configured to open a modal window where an entire record page can be opened in view or edit mode. 

![Image](https://user-images.githubusercontent.com/1500447/198842330-a98e8707-5d48-4a4c-adc6-a45bbe4dbefe.png)
Record list configuration 

 - [x] Change record list configurator to support one of three modes (same window, new tab, modal)
 - [x] Ensure old config (new tab) is gracefully handled (respected when loaded and converted on change/save)
 - [x] Implement opening record page in a modal
 - [x] Ensure all functions (delete, cone, edit, add-new) work

**Comment by yonkov** [comment]
## Pull Request Link

https://github.com/cortezaproject/corteza/pull/524

## Screenshots of the implementation

![Screenshot from 2022-11-11 13-52-31](https://user-images.githubusercontent.com/26258032/201339573-ca34dab2-e48a-4365-83a2-50f00f0baa0f.png)

![Screenshot from 2022-11-11 13-48-19](https://user-images.githubusercontent.com/26258032/201339595-92f31f45-f127-42a5-9331-8f8adb94246f.png)

## Changelog

**What was added?**

When adding a "record list" page block in the Compose page builder, a dropdown field has been added with three options:

- open record in the same tab
- open record in a new tab
- open record in a modal

The default option is to open in the same tab.

_Note: The first two options already existed and are handled gracefully, e.g. respected for existing record lists_

The new thing here is the third option - "open record in a modal". When this option is selected and the user goes to a record list page or a page that displays record lists, he can click on a specific record and it will open as a modal. From the modal, the user can do whatever he wants with the existing record (edit, delete, clone) or even add a new record.

**How it was added?**

In the Compose app, a root event was emitted from the RecordList component that emits an event with all the necessary information to a new modal component, which has been called from the public page. The modal is then able to display the record and its information. In order to do this, instead of using routes, the ViewRecord component is added as a child component to the modal and it receives its props from the modal itself.

**Why it was added?**
We believe that this option will improve user experience and make record entry a bit more intuitive, since the user will remain on the record list page while doing the changes. In this way, he will not get overwhelmed by being redirected to a different page.

**Comment by Bojan-Svirkov** [comment]
This works flawlessly. Good job @yonkov

**Comment by Bojan-Svirkov** [comment]
Added entry to the CL. Moving the ticket to `Done`.
