### ISSUE TITLE
Add support for navigational page block [PlanID:2023.3/11/2.7]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#449]
Introduce new page block type for showing one or two level of dynamic and static navigation 

Inspired by bootstrap's [nav component](https://bootstrap-vue.org/docs/components/nav).

**List configuration**
 - [x] Add tab right of **general** - "Navigation"
 - [x] options for align, vertical, fill, pills, small, tabs
 - [x] Default properties for all items
   - [x] disabled
   - [x] text variant or colour
   - [x] background variant or colour
 - [x] List items can be sorted (drag & drop)

**Supported navigation item types**
 - [x] **Text**
 - [x] **Delimiter** (only inside dropdown)
 - [x] **URL**
   - [x] new window/tab
 - [x] Compose **page** in the same namespace
   - [x] new window/tab
   - [x] use `to` prop on `<b-nav-item>` to to ensure internal router is used
   - [x] select a page to be used, keep reference (ID)
   - [x] option to show list of child pages in-place (1 level only)
   - [x] option to show referenced page as dropdown with subpages 
 - [x] **Dropdown**
   - [x] Only **text** and **URL**
   - [x] If used in combination with compose page, ensure there is no 2nd level
   - [x] Support drop(left|right|up) prop
 
**Item types properties**
Each item can override the default (see above) item properties

 - [x] Ability to remove explicit property value (and use the default)

**Comment by kelanik8** [comment]
https://github.com/cortezaproject/corteza/pull/584

**Comment by kelanik8** [comment]
![image](https://user-images.githubusercontent.com/23015247/205050512-ace8c5a6-53e1-48d6-b39c-e39c3a4c02b5.png)
![image](https://user-images.githubusercontent.com/23015247/205050524-f375af78-9e17-4fb0-bdb0-db84747ae5d7.png)
![image](https://user-images.githubusercontent.com/23015247/205050539-b3d0504a-c88b-414d-bf8a-569845c887c5.png)

**Comment by Bojan-Svirkov** [comment]
THere are couple more things that needs to be addressed and it was already discussed with Tolu. So once everything is addressed feel free to move the ticket back again to in QC

**Comment by Bojan-Svirkov** [comment]
Retested again and couple more issues arise here so we will try to address those and after that will need to be retested again.
The found issues for now are:

- The display block as a card doesn't work as expected.

- I don't see the difference between opening up things in a new window or a new tab (this is connected with the browser type, will be discussed further).

- When I set navigation items of type URL, the open in same tab doesn't do anything (and if you have first a configuration for compose page and you switch to URL later on, the URL tab is still stuck with the compose page and the URL is not even shown. Tolu will be addressing this one)

- Compose page doesn't show the subpages (this was related with the configuration of a subpage. This is probably fine, will be retested again)

- Display options for appearance doesn't look to be doing the correct output. (this is probably fine, since the difference between the tabs, pills and small are actually behind the curtains so we cannot really see what is going on just by looking at the design.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. The only thing now left is the CL entry.

**Comment by kelanik8** [comment]
Changelog:

**What changed**
- Updated the page blocks with a navigation page block

**Why did it change**
- To add new support for a fully customizable navigation page block with multiple navigation item type and customizatible options for the navigation list items

**How did it change**
- Added a new configurator with the required configuration options for the navigation page block and the base which displays the navigational block with the styles and configuration options

**Comment by Bojan-Svirkov** [comment]
Added CL
