### ISSUE TITLE
Add support for Chart drill-down [PlanID:2023.3/22/1.6]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#461]
An integrator can select a specific chart on a report to support interaction (or a drill-down). This allows users to click on certain parts of the chart and explore the data that is aggregated on the chart in a tabular view.

----

Example: 

The report chart shows the percentage of people grouped by age range. The end user clicks on one of the ranges on the chart and connected table showing users interactively filter the list by the selected range. 

![Image](https://user-images.githubusercontent.com/1500447/201076912-d43edacb-6f2b-41ef-9f0e-cfc35e7fedec.png)

**Comment by Fajfa** [comment]
Progress

![Image](https://user-images.githubusercontent.com/15791641/214331461-83b4461f-e49b-41a1-9e40-9e5926d9a74e.gif)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. 
@Fajfa , if you can just now include the CL entry it would be great.

**Comment by Fajfa** [comment]
Added

- What
Added ability to drill down chart, by clicking on an data entry inside on the chart, based on the configuration
it can either filter an existing record list on the page, that is showing the records from the same module as the chart,
or open a new record list in a modal.

- Why
To make it easier for users to filter record lists based on chart data, in order to view the details of said data.

**Comment by Bojan-Svirkov** [comment]
Added CL entry.
