### ISSUE TITLE
When editing a deleted integration gateway route, the route gets restored automatically

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#471]
When you open a deleted  integration gateway route, and lets say you edit/change the name of the route and press submit, the integration gateway route gets restored automatically even though you haven't un-deleted it. 

This is not the case with the un-deletion with the other admin system settings for example users and applications.

**Comment by petergrlica** [comment]
**What changed**
Deleted status on apigw route update gets preserved

**Why did it change**
Apigw route needed to handle deleted status on update in consistency with other subsystems (ie applications, users, ...)

**How did it change**
Fixed the part of apigw service that handles route updates

Commit: https://github.com/cortezaproject/corteza/commit/16257e9d4b49dea0038a9ddb4372b5f3ec949915

**Comment by Bojan-Svirkov** [comment]
@petergrlica , now when you make changes and press submit, the route doesn't get restored and the updated at changes, but the change is not really saved. Is that the expected behavior here? to not be able to change let's say name on a deleted route, I guess not? So if I have a name /test, and I change it to /example and press submit, the route doesn't get restored (which is okay), the updated at changes (which is okay), but the value is back again to /test instead to the new one /example. Can you look into this one more time.

**Comment by Bojan-Svirkov** [comment]
Added entry to the CL

**Comment by petergrlica** [comment]
Added necessary changes @Bojan-Svirkov, please feel free to check again, the commit: https://github.com/cortezaproject/corteza/commit/fe6e13aa3309a6f0fa9d7c7c21498e7c4e6bbaaf

**Comment by Bojan-Svirkov** [comment]
@petergrlica now everything works as expected. I am moving the card to **Done** and you can merge the changes. Thanks
