### ISSUE TITLE
Support for additional chart Types [PlanID:2023.3/23/1]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#482]
Explore options for implementation of the following EChart types in Compose and Reporter:

- Radar, 
- Polar, 
- Horizontal Bar, 
- Trend Lines in Charts, 
- Scatter, Bubble, 
- Heatmap, 
- Calendar Heatmap, 
- Time Series

This on needs to be researched first.

**Comment by katrinDY** [comment]
### Findings:

- **Radar** - type of chart
  - configs
     - radar: { shape: circle/polygon, indicator: [ {name: 'Sales (sales)',  min: 0, max: 100 } ] }
	   - indicator is used for assigning multiple variables (dimensions)
	   - min and max are optional to configure
	      - max should be set manually
	      - min by default is 0
	   - series: [ { type: radar } ]
        - example: [Basic Radar Chart - Apache ECharts Demo](https://codepen.io/lennyhorstink/pen/NWBYqaN)

---

- **Polar** - addition to chart
  - configs
    - add  `polar: {}` after legend {}
    - angleAxis: { type: 'value' }
    - radiusAxis: {}
    - series: [
	{
		coordinateSystem: 'polar',
	  	 type: '<type of chart>',
			 data: data
	}
       ]
  - notes
    - this is gonna be used for bar charts
  - example [Radial Polar Bar Label Position - Apache ECharts Demo](https://codepen.io/lennyhorstink/pen/MWBVoyG)

---

- **Horizontal Bar** - bar type of chart; the data is displayed horizontally instead of vertically (by default)
  - configs
    - set  `type: 'value'`  of yAxis and  `type: 'category'` to xAxis
  - example: [Examples - Apache ECharts](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack)

---

- **Trend Lines in Charts** - type of chart is custom
  - configs
     - { type: 'custom', name: 'trend', renderItem() - function to calculate the position of the trend line}
   - example: [Examples - Apache ECharts](https://echarts.apache.org/examples/en/editor.html?c=custom-bar-trend)

---

- **Scatter** - type of chart
  - simple scatter chart
	- configurations
		- xAxis and yAxis; both can be {}; no need to define anything inside them
		- series: [ { symbolSize: 60, data: [ [10.0, 8.04], [8.07, 6.95] ], type: 'scatter' } ]
			- symbolSize determines the size of each dot
	- example: [Examples - Apache ECharts](https://echarts.apache.org/examples/en/editor.html?c=scatter-simple)
  - scatter chart with quadrant
	- example [Basic Scatter Chart - Apache ECharts Demo](https://codepen.io/lennyhorstink/pen/bGjvVbq)
	- configs
		- 5 objects
			- the first - containing the size and coordinate of the dots, the type of chart
			- the rest 4 {} - containing the sector of the chart, it’s coordinates, name and type of chart
				- markArea - marks a sector in the chart
				- itemStyle - contains styles for the concrete item, in this case for the area
				- data [] - holds the coordinates and name of the chart sector
	- notes
		- The mark areas are created like this because of this comment: https://github.com/apache/echarts/issues/7793#issuecomment-367657294
		- more info on quadrant charts: [IBM Documentation](https://www.ibm.com/docs/en/cognos-analytics/11.0.0?topic=types-quadrant-charts)

---

- **Calendar Heatmap** - type of chart
  - configs
    - getVirtualData() - retrieves and prepares data for chart (passed to series{})
    - visualMap { orient: 'horizontal' } and calendar {} are added after tooltip
    - `type: 'heatmap'`, and  `coordinateSystem: 'calendar'` are set in series
  - example [Examples - Apache ECharts](https://echarts.apache.org/examples/en/editor.html?c=calendar-heatmap) 

---

- **Time Series** - chart of type Line
  - configs
    - set `xAxis: { type: 'time' }` - this will give us better formatting for time and a different tick calculation method 
  - example https://echarts.apache.org/examples/en/editor.html?c=area-time-axis

---

- **Zoom in/out chart data** - add to line chart
  - configs
    - add dataZoom under yAxis
  - example: https://echarts.apache.org/examples/en/editor.html?c=area-time-axis

**Comment by Fajfa** [comment]
Added Scatter and Radar charts. Also added "Auto" grouping which is the Time series point.
Also added timeline on charts with axis and horizontal option on the y-axis

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
Added:

{
      "what": [
        "support for radar and scatter type charts.",
        "Also added `Auto` grouping which is the Time series point and added timeline on charts with axis and horizontal option on the y-axis."
      ],
      "why": [
        "to give users more options when displaying data with charts."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1148/commits/70cd9b8e87cac48d073bee7afc6197a4ed5adeb0",
        "https://github.com/cortezaproject/corteza/pull/1148/commits/df6eaace7f1038f035564d7ff91d52ce4f7480b5",
        "https://github.com/cortezaproject/corteza/pull/1148/commits/68f570073a1f3844f65f3fe2c89be2efb582fd94",
        "https://github.com/cortezaproject/corteza/pull/1148/commits/aa5027811fe239550e702e88f7764f909b53e1bd"
      ]
    }
