### ISSUE TITLE
Cannot export user from a concrete db

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#607]
## Server logs
```
runtime error: invalid memory address or nil pointer dereference
goroutine 1462 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x19
github.com/cortezaproject/corteza/server/pkg/api/server.panicRecovery({0x6265ad0, 0xc0024649c0}, {0x62633c0, 0xc000cad5e0})
        github.com/cortezaproject/corteza/server/pkg/api/server/middleware.go:43 +0x111
panic({0x5928800, 0x72960a0})
        runtime/panic.go:884 +0x212
github.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc001c87910, 0x538024b?, 0xc00247e500)
        github.com/getsentry/sentry-go@v0.13.0/http/sentryhttp.go:117 +0xf0
panic({0x5928800, 0x72960a0})
        runtime/panic.go:884 +0x212
github.com/cortezaproject/corteza/server/pkg/envoy/resource.NewRole(0x0)
```

## URL
http://localhost:3000/api/system/users/export/export.zip?jwt=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJRCI6IjMwODIyODA0MjY1MDU1MDM3NCIsImV4cCI6MTY3MDMyOTgzMiwiaWF0IjoxNjcwMzIyNjMyLCJpc3MiOiJjb3J0ZXphcHJvamVjdC5vcmciLCJqdGkiOiJNVEpJWUpHWFpHTVRPREsyWUkwWk0yUTVMVEs0TkdJVE0ySktOV0UzWkRVME5ES1oiLCJyb2xlcyI6WyIzMDgyMjgwMzkzNjIyODE1NzQiXSwic2NvcGUiOiJwcm9maWxlIGFwaSIsInN1YiI6IjMwODIyODEwOTAzNzk5NDA4NiJ9.SkpWevKaNdTM8t_pTbWJtpFlQSAetFsYc_s1FnJg-lBA6Rd4IWcUAywnHQVdX1apcKyCilo-CfVYDiWTXtonpw&inclRoleMembership=true&inclRoles=false

## Notes
- this happens only to a specific user without any role, MFA or auth providers
- the user has email, full name and handle
- checked the user in the db and everything looks okay
- cypress tests aren't the cause of the issue

**Comment by katrinDY** [comment]
@katrinDY to add a db dump; make sure db has the issue reproducible

**Comment by katrinDY** [comment]
db dump https://gist.github.com/katrinDY/4fe250f272746412684b9be2cd2e677f

**Comment by tjerman** [comment]
The issue was caused by an archived (`313770082071218690`) and a deleted (`313771029497383426`) role assigned to a user (`308257738742300774`).

The export logic can resolve unresolved resources on the fly and I didn't exclude this _edge case_ which caused the server to panic.

After the patch, it works just fine.

![Image](https://user-images.githubusercontent.com/12545711/211534274-797898f3-ce64-43e9-9c1d-7f0c301e3cf9.png)

monorepo

2022.9.x commit `14326713e`

**Comment by Bojan-Svirkov** [comment]
Tested with the next reproduction steps:

1. go to admin webapp, create a new user and two new roles
2. assign the two new roles to the user
3. delete one of the new roles
4. archive one of the new roles
5. try to export

I am able to export the user which means the issue is resolved and we can move this ticket to **Done**.
