### ISSUE TITLE
Workflow debugging: if a step panics the "running spinner" never stops

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#622]
## Description
I forced a panic (in code) in the function step which threw the error that the session was not found.

## Note
We do some special handling for panic cases (if we didn’t change this already) so this is probably an edge case.

## Error log
```
Error: step 4 crashed: A
14:15:42.844	DEBUG	workflow.session.exec	executed	{"workflowID": 305782399537529971, "runnerID": 303885435040449651, "runnerRoles": [303885395395953779, 303885395396019315], "sessionID": 305784462799553651, "stateID": 305784462799619187, "stepID": 4, "functionRef": "composeRecordsSearch", "functionKind": "function", "execTime": "8.256979ms"}
goroutine 949 [running]:
```

## Screenshot of error
![Image](https://user-images.githubusercontent.com/85161724/206721970-3aa989c4-be4c-4955-aa6f-d9787bed80f3.png)

**Comment by tjerman** [comment]
This can only happen in extreme edge cases where our built in functions would panic due to some implementation issue. To resolve it on back-end, we'd need to do quite a bit of refactoring in terms of panic recovery and session management which won't be easy for any of us.

What I'd suggest is we add an exception to this edge-case where the execution request _fails successfully_ but can't obtain the session info since it was never created because of panic recovery.

**Comment by tjerman** [comment]
The workflow now no longer hangs and recovers properly

![image](https://user-images.githubusercontent.com/12545711/212304195-fb875f6a-b15c-4da7-8889-21986edf15bf.png)

@Bojan-Svirkov for QC, at this line https://github.com/cortezaproject/corteza/blob/2022.9.x-wf-panic-recovery/server/system/automation/users_handler.go#L167 add `panic("AAAAA")`

**Comment by tjerman** [comment]
## Fixed

### What

workflow execution never completing in case of a workflow step crashing due to an internal error.

### How

adding additional error handlers for this specific edge-case

### Refs

2022.9 monorepo commit `a6bd90560`

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this is now fixed. Added Cl.
