### ISSUE TITLE
Cannot undelete a sensitivity level

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#628]
## Cause of the problem
FE is calling the delete endpoint instead of undelete. Look at User editor and do the same with sensitivity

## Reproduction steps
![Image](https://user-images.githubusercontent.com/85161724/206729686-6ea1b189-aec6-4435-8ff0-2588703f066f.gif)

**Comment by tjerman** [comment]
Investigating now...

**Comment by tjerman** [comment]
Trivial issue, fixed it directly https://github.com/cortezaproject/corteza/commit/7eb26e6ef

## Fixed

### What

Fixed sensitivity level undelete prompting a not found error due to an invalid HTTP request.

### How

Properly handled the different sensitivity level states to call the correct endpoint -- kept consistent with other resources (user undelete for example.

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. CL entry has been also added. Moving the card to **Done**. @tjerman  If everything is merged, feel free to close this issue.
