### ISSUE TITLE
Add echarts to admin active users chart and fix date not converted issue

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#799]
## Issue on 229-qc

![Image](https://user-images.githubusercontent.com/85161724/213176314-478e4b60-9df7-41ec-916f-476131c44281.png)

## TODO
- [x] substitute chartjs with echarts
- [x] fix convert issue

**Comment by Fajfa** [comment]
@Bojan-Svirkov To be tested on both 2022.9.6 and 2023.3

Changed:
- What: Replaced the usage of chart.js on admin dashboard with e-charts
- Why: To remove all places where we used to use chart.js since we transitioned to apache echarts
- How: The chart is now in line with other charts in corteza, the date tooltips are now also correctly displayed

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this works as expected. CL was also added, moving the card to **Done**.
