### ISSUE TITLE
Cannot import namespace

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#844]
## Version
_22.9.6_

## Steps to reproduce
_With a new namespace_

1. Create a namespace
2. Add a module with a text field
3. Create a page for the module
4. Add a RL and configure it to show the text field
5. Save the RL changes
6. Export this namespace
7. Delete it
8. Import it under a different name and handle
9. Visit the namespace's home page and see the error `Could not load record list: can not change module on a record`

_With Case management namespace_
1. Export the namespace
2. Import it under a diff name and handle
3. Go to the Home page and see the same error

## Cause of the issue
We export records alongside the namespace, and those records have the wrong moduleID saved

**Comment by tjerman** [comment]
The actual issue was that Envoy didn't set model constraints which caused it to fetch records for any module (registered under the default con).

## Fixed

### What

record lists raising `Could not load record list: can not change module on a record` when interacting with an imported namespace.
The issue was caused because the import logic didn't define any model constraints.

## How

by making the import logic apply model constraints when defining the model, as well as defining the record revisions model.

## Refs

2022.9.x monorepo commit `a554e289c`

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL was also added so moving the card to Done.
