### ISSUE TITLE
Add date input field for reminders

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#851]
## Description
This will allow users to set reminders for more than 24h

## Ref to forum
https://forum.cortezaproject.org/t/how-can-i-modify-the-reminder-time-dropdown/1253/3?u=katrinyordanova

**Comment by yonkov** [comment]
Probably no need for backend work here, since there is a field "RemindAt" that gets updated when there is a custom date input field.



![Image](https://user-images.githubusercontent.com/26258032/219413496-2a906ce9-98cc-4548-8a68-06bf98a9df95.png)

**Comment by yonkov** [comment]
Update: I might need an additional property to store the user's input, since we would need to retrieve it once the reminder is opened again. It might also work to convert the `remindAt` property as an object that contains the timestamp and the user's input but another property, e.g. `customExpiryDate:2w` would be better.

![Image](https://user-images.githubusercontent.com/26258032/220960830-b0aa2fef-c1c8-4bd4-9350-37aa49a313c8.png)

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected. CL entry has been also added.
